### ISSUE TITLE
Failures in stand alone scheduled builds

### ISSUE THREAD

**Issue by dguest** [lwtnn/lwtnn#155]
I'm being notified in failures in runs [#298](https://github.com/lwtnn/lwtnn/actions/runs/1299390807) and [#299](https://github.com/lwtnn/lwtnn/actions/runs/1301700932). The failures say something about the MD5 hash not matching. Someone should try to figure out what changed. Maybe @matthewfeickert if he has time before I do.

**Comment by matthewfeickert** [comment]
The failures are due to an Eigen hash difference

```
-- verifying file...
       file='/home/runner/work/lwtnn/lwtnn/build/externals/src/eigen-3.3.7.tar.bz2'
-- MD5 hash of
    /home/runner/work/lwtnn/lwtnn/build/externals/src/eigen-3.3.7.tar.bz2
  does not match expected value
    expected: 'b9e98a200d2455f06db9c661c5610496'
      actual: 'b11361231583d0da2292e662e941957e'
-- Hash mismatch, removing...
CMake Error at Eigen-stamp/download-Eigen.cmake:170 (message):
  Each download failed!
```

and are happening during the build step

https://github.com/lwtnn/lwtnn/blob/be77babd213d6b88f09a4590227c4bb52cf2de66/.github/workflows/ci.yml#L84-L85


which is activating the following CMake build options in the build script

https://github.com/lwtnn/lwtnn/blob/be77babd213d6b88f09a4590227c4bb52cf2de66/tests/build-cmake.sh#L27-L29

turning on 

https://github.com/lwtnn/lwtnn/blob/be77babd213d6b88f09a4590227c4bb52cf2de66/CMakeLists.txt#L85-L97

However, I'm confused as to why these errors are happening, as if I try to validate against them

```console
$ curl -sLO https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2
$ md5sum eigen-3.3.7.tar.bz2 
b9e98a200d2455f06db9c661c5610496  eigen-3.3.7.tar.bz2
```

which matches as exptected. :?

**Comment by matthewfeickert** [comment]
@dguest The ["scheduled" CI workflow](https://github.com/lwtnn/lwtnn/actions/workflows/ci.yml?query=event%3Aschedule) for run 300 [is passing](https://github.com/lwtnn/lwtnn/actions/runs/1305859965). I'd give it another run (actually just trigger it to run now with workflow dispatch from the Actions view &mdash; this requires you to do it given permissions) and if it passes then I'd say that this was a passing fluke due to some issue on https://gitlab.com 's servers.

**Comment by matthewfeickert** [comment]
As the CI is passing fine for me at the moment on my synced fork I think this can get closed @dguest and chocked up to GitLab server error.
